<!--
 * @Author: liwz
 * @Date: 2024-09-25 16:54:30
 * @LastEditors: liwz
 * @LastEditTime: 2024-09-29 14:49:00
 * @FilePath: /study_new/promise/04-promise的封装/10-promise封装-catch方法与异常穿透/index.html
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>10-promise封装-catch方法与异常穿透</title>
    <script src="./promise.js"></script>
  </head>
  <body>
    <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          // resolve('ok')
          reject('error')
        }, 1000)
      })

      p.then(value => {
        console.log(111)
      })
        .then(value => {
          console.log(222)
        })
        .then(value => {
          console.log(333)
        })
        .catch(reason => {
          console.warn(reason)
        })
    </script>
  </body>
</html>
